name: testing

on:
  push:

  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  test:
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies & package
        run: |
          python -m pip install --upgrade pip
          pip install .[tests,dev]
          pip install .

      - name: Lint
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Test
        run: |
          pytest tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.1.1
        if: matrix.python-version == '3.11'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Matgenix/atomate2-turbomole
